#!/usr/bin/env python
# -*- coding: utf-8; -*-
#
# This file is part of SAMS.
#
# Copyright 2020 Sourcefabric z.u. and contributors.
#
# For the full copyright and license information, please see the
# AUTHORS and LICENSE files distributed with this source code, or
# at https://www.sourcefabric.org/superdesk/license

version: 1
disable_existing_loggers: True
formatters:
  simple:
    format: '%(asctime)s level=%(levelname)s pid=%(process)d function=%(name)s:%(module)s:%(funcName)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    stream  : ext://sys.stdout
    formatter: simple
loggers:
  sams:
    handlers: [console]
    level: DEBUG
    propagate: no
  werkzeug:
    handlers: [console]
    level: DEBUG
    propagate: no
  superdesk:
    handlers: [console]
    level: DEBUG
    propagate: no
root:
  handlers: [console]
